wget http://www.hapmap.org/genotypes/latest/fwd_strand/non-redundant/genotypes_chr1_CEU_r21_nr_fwd.txt.gz
wget http://www.hapmap.org/genotypes/latest/fwd_strand/non-redundant/genotypes_chr2_CEU_r21_nr_fwd.txt.gz
wget http://www.hapmap.org/genotypes/latest/fwd_strand/non-redundant/genotypes_chr3_CEU_r21_nr_fwd.txt.gz
wget http://www.hapmap.org/genotypes/latest/fwd_strand/non-redundant/genotypes_chr4_CEU_r21_nr_fwd.txt.gz
wget http://www.hapmap.org/genotypes/latest/fwd_strand/non-redundant/genotypes_chr5_CEU_r21_nr_fwd.txt.gz
wget http://www.hapmap.org/genotypes/latest/fwd_strand/non-redundant/genotypes_chr6_CEU_r21_nr_fwd.txt.gz
wget http://www.hapmap.org/genotypes/latest/fwd_strand/non-redundant/genotypes_chr7_CEU_r21_nr_fwd.txt.gz
wget http://www.hapmap.org/genotypes/latest/fwd_strand/non-redundant/genotypes_chr8_CEU_r21_nr_fwd.txt.gz
wget http://www.hapmap.org/genotypes/latest/fwd_strand/non-redundant/genotypes_chr9_CEU_r21_nr_fwd.txt.gz
wget http://www.hapmap.org/genotypes/latest/fwd_strand/non-redundant/genotypes_chr10_CEU_r21_nr_fwd.txt.gz
wget http://www.hapmap.org/genotypes/latest/fwd_strand/non-redundant/genotypes_chr11_CEU_r21_nr_fwd.txt.gz
wget http://www.hapmap.org/genotypes/latest/fwd_strand/non-redundant/genotypes_chr12_CEU_r21_nr_fwd.txt.gz
wget http://www.hapmap.org/genotypes/latest/fwd_strand/non-redundant/genotypes_chr13_CEU_r21_nr_fwd.txt.gz
wget http://www.hapmap.org/genotypes/latest/fwd_strand/non-redundant/genotypes_chr14_CEU_r21_nr_fwd.txt.gz
wget http://www.hapmap.org/genotypes/latest/fwd_strand/non-redundant/genotypes_chr15_CEU_r21_nr_fwd.txt.gz
wget http://www.hapmap.org/genotypes/latest/fwd_strand/non-redundant/genotypes_chr16_CEU_r21_nr_fwd.txt.gz
wget http://www.hapmap.org/genotypes/latest/fwd_strand/non-redundant/genotypes_chr17_CEU_r21_nr_fwd.txt.gz
wget http://www.hapmap.org/genotypes/latest/fwd_strand/non-redundant/genotypes_chr18_CEU_r21_nr_fwd.txt.gz
wget http://www.hapmap.org/genotypes/latest/fwd_strand/non-redundant/genotypes_chr19_CEU_r21_nr_fwd.txt.gz
wget http://www.hapmap.org/genotypes/latest/fwd_strand/non-redundant/genotypes_chr20.txt.gz
wget http://www.hapmap.org/genotypes/latest/fwd_strand/non-redundant/genotypes_chr21.txt.gz
wget http://www.hapmap.org/genotypes/latest/fwd_strand/non-redundant/genotypes_chr22.txt.gz
wget http://www.hapmap.org/genotypes/latest/fwd_strand/non-redundant/genotypes_chrM.txt.gz
wget http://www.hapmap.org/genotypes/latest/fwd_strand/non-redundant/genotypes_chrX.txt.gz
wget http://www.hapmap.org/genotypes/latest/fwd_strand/non-redundant/genotypes_chrY.txt.gz
