#! /srv/www/bin/R-devel/bin/R

tag(html)
tag(head)
tag('body style="color: rgb(0, 0, 0); background-color: rgb(192, 192, 
192);" alink="#358cff" link="#358cff" vlink="#990099"')

tag(title)
cat("GGtools")
untag(title)
untag(head)

tag('form action="http://localhost/cgi-bin/R.cgi/ggtools3.R" 
method="get"')
cat('Chromosome&nbsp;&nbsp; ')
tag('SELECT NAME="chromosome"')
tag('OPTION VALUE="1"')
cat("1")
tag('OPTION VALUE="2"')
cat("2")
tag('OPTION VALUE="3"')
cat("3")
tag('OPTION VALUE="4"')
cat("4")
tag('OPTION VALUE="5"')
cat("5")
tag('OPTION VALUE="6"')
cat("6")
tag('OPTION VALUE="7"')
cat("7")
tag('OPTION VALUE="8"')
cat("8")
tag('OPTION VALUE="9"')
cat("9")
tag('OPTION VALUE="10"')
cat("10")
tag('OPTION VALUE="11"')
cat("11")
tag('OPTION VALUE="12"')
cat("12")
tag('OPTION VALUE="13"')
cat("13")
tag('OPTION VALUE="14"')
cat("14")
tag('OPTION VALUE="15"')
cat("15")
tag('OPTION VALUE="16"')
cat("16")
tag('OPTION VALUE="17"')
cat("17")
tag('OPTION VALUE="18"')
cat("18")
tag('OPTION VALUE="19"')
cat("19")
tag('OPTION VALUE="20"')
cat("20")
tag('OPTION VALUE="21"')
cat("21")
tag('OPTION VALUE="22"')
cat("22")
untag(SELECT)
tag(br)
cat("gene")
tag('INPUT type="text" name="gene"')
tag(br)
cat("Number of SNPs to report")
tag('INPUT type="text" name="nsnps"')
tag(br)
tag('INPUT type="submit" value="Send"')
untag(form)
