%\VignetteIndexEntry{GGtools Bioinfo Application note support }
%\VignetteDepends{}
%\VignetteKeywords{Genetical genomics,SNP,expression}
%\VignettePackage{GGtools}


%
% NOTE -- ONLY EDIT THE .Rnw FILE!!!  The .tex file is
% likely to be overwritten.
%
\documentclass[12pt]{article}

\usepackage{amsmath,pstricks}
% With MikTeX 2.9, using pstricks also requires using auto-pst-pdf or running
% pdflatex will fail. Note that using auto-pst-pdf requires to set environment
% variable MIKTEX_ENABLEWRITE18=t on Windows, and to set shell_escape = t in
% texmf.cnf for Tex Live on Unix/Linux/Mac.
\usepackage{auto-pst-pdf}
\usepackage[authoryear,round]{natbib}
\usepackage{hyperref}


\textwidth=6.2in
\textheight=8.5in
%\parskip=.3cm
\oddsidemargin=.1in
\evensidemargin=.1in
\headheight=-.3in

\newcommand{\scscst}{\scriptscriptstyle}
\newcommand{\scst}{\scriptstyle}


\newcommand{\Rfunction}[1]{{\texttt{#1}}}
\newcommand{\Robject}[1]{{\texttt{#1}}}
\newcommand{\Rpackage}[1]{{\textit{#1}}}
\newcommand{\Rmethod}[1]{{\texttt{#1}}}
\newcommand{\Rfunarg}[1]{{\texttt{#1}}}
\newcommand{\Rclass}[1]{{\textit{#1}}}

\textwidth=6.2in

\bibliographystyle{plainnat} 
 
\begin{document}
%\setkeys{Gin}{width=0.55\textwidth}

\title{Computations related to the Bioinformatics Applications
Note, 2009}
\author{VJ Carey stvjc at channing.harvard.edu}
\maketitle

The main illustrations in the Applications note involve
a gene set.  All chunks have eval=FALSE; to run this code, please
manually reset.

<<geta,eval=FALSE>>=
library(GGtools)
library(GSEABase)
load(system.file("genesets/hla2set.rda", package="GGtools"))
hla2set
@

We need to filter the full HapMap CEU cohort to founders:
<<aasd,eval=FALSE>>=
library(GGdata)
data(hmceuB36)
hmFou = hmceuB36[, which(hmceuB36$isFounder == TRUE)]
@

Now we run the tests:
<<dorun,eval=FALSE>>=
hla2run = gwSnpTests(hla2set~male, hmFou, snpdepth(250))
@

\end{document}
